name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ZIP
        run: |
          zip -r noveya-health-module-${GITHUB_REF_NAME}.zip . -x ".git/*"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: noveya-health-module-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
